### ISSUE TITLE
Error during load: Could not create the database table: validator/converter not found: u'scheming_multiple_choice_output'

### ISSUE THREAD

**Issue by kimepe** [ckan/ckanext-xloader#64] opened 2018-11-19 19:21 UTC
I've just install XLoader on a clean install. While trying to push a CSV resource to the DataStore, I get the following error message: 
Erreur : File "/usr/lib/ckan/default/src/ckanext-scheming/ckanext/scheming/validation.py", line 319, in get_validator_or_converter raise SchemingException('validator/converter not found: %r' % name) SchemingException("validator/converter not found: u'scheming_multiple_choice_output'",)

The log which resides under says at one point: 
Error during load: Could not create the database table: validator/converter not found: u'scheming_multiple_choice_output'

Any idea on how to fix this?

**Comment by davidread** [comment] 2018-11-20 07:39
I've not tried it in combination with scheming extension, I'm afraid. You could try putting in a pdb breakpoint and getting a full stacktrace. It would also be helpful to have the full output of the load log.

**Comment by metaodi** [comment] 2018-11-21 13:47
Linking the same ticket on ckanext-scheming: https://github.com/ckan/ckanext-scheming/issues/199

**Comment by metaodi** [comment] 2018-11-21 13:49
I can confirm that we occasionally get this error on one of our instances, but I didn't yet have the time to debug it.

**Comment by metaodi** [comment] 2018-11-24 06:36
On our system we upraded ckanext-scheming to the latest version of master and didn't get the error since. But we still don't know the cause and wheter it's fixed now or not. Keep you posted.

**Comment by stefina** [comment] 2018-11-29 10:13
Our issue was this one https://github.com/ckan/ckanext-scheming/issues/183 
In that issue it is also mentioned, that it only occurs randomly which was the case for us. (some caching-weirdness..)
@kimepe Not sure if that fix helps you, too, as you are describing another error-message, but it might be worth debugging in that direction.

**Comment by kimepe** [comment] 2018-11-29 16:18
@stefina Thanks. I'll look into that. In the meantime, I finally switched back to the original DataPusher, since the client wanted it so bad. I'll keep experimenting around to see if I can get this to work. And by the way, thanks to all of you for suggesting so many things.
@davidread Sorry, but I'm not quite sure on how to add 'pdb breakpoint and getting a full stacktrace'. I'm really just discovering CKAN and its universe, and there are so many things I still need to learn/understand. If you or anyone else has a link or process to get this done, I would be more than happy to provide the required details

**Comment by kimepe** [comment] 2018-11-29 16:41
> @kimepe In an effort to replicate this, could you paste an obfuscated config file and include some detail on your system?

[production.txt](https://github.com/ckan/ckanext-xloader/files/2629992/production.txt)
Here is the production.ini file used at the time.
System-wise, we are  trying to set a portal 

- combining Wordpress and CKAN : Wordpress handles the home page and a couple of other pages, and CKAN handles all the datasets related pages and features
- CKAN related pages are accessible at http://mywonderful.platform/recherche, while Wordpress serves http://mywonderful.platform
- We have developed a custom theme on top of CKAN (wonderful_theme) and it relies on a couple of other plugins to achieve few operations, thus the use of scheming_datasets, hierarchy_display (though this one has been breaking the website so often), and a couple of other ones
- OS : Ubuntu 18.04 LTS
- CKAN : 2.8.1
- Wordpress : 4.9.5

Is there anything else you might want to know?

**Closed** 2024-11-23 01:08 UTC
